# Generated by Django 3.1.7 on 2021-03-18 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_timesofwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.timesofwork', verbose_name='время приема'),
        ),
    ]
